# apt:
#   - htop
#   - build-essential
#   - curl 
#   - lsb-release
#   - wget

deb:
  - https://github.com/wimpysworld/deb-get/releases/download/0.3.9/deb-get_0.3.9-1_all.deb
  - https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megasync-xUbuntu_22.04_amd64.deb
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


execute:
  - deb-get install 