#!/bin/python3

import yaml
import apt
import sys
from urllib.request import urlretrieve
import subprocess as sp
import os

def log(message: str):
    print(">>> " + message)

def read_config():
    with open('config.yaml', 'r') as file:
        return yaml.safe_load(file)
    
def install_apt_package(package_name: str):
    cache = apt.Cache()
    cache.open()

    if cache[package_name].is_installed:
        log(package_name + ' already installed')
    else:
        log('Installing: ' + package_name)
        pkg = cache[package_name]
        pkg.mark_install()
        try:
            cache.commit()
        except Exception:
            print >> sys.stderr, "Sorry, package installation failed [{err}]".format(err=str(Exception))
        
def install_deb_package(deb_url: str):
    log('Installing deb: ' + deb_url)
    path, headers = urlretrieve(deb_url)
    content_dis = headers['Content-Disposition']
    filename_pos = content_dis.find('filename=')
    fileName = content_dis[filename_pos + 9:]
    urlretrieve(deb_url, fileName)
    sp.call(["sudo","dpkg","-i", fileName])
    os.remove(fileName)

def execute(command: str):
    log('Executing: ' + command)
    sp.call([command])

def main():
    print("Reading config")
    config = read_config()
    print("Reading read")

    print(config)

    if 'apt' in config:
        for package in config['apt']:
            install_apt_package(package)
    
    if 'deb' in config:
        for deb in config['deb']:
            install_deb_package(deb)

    if 'execute' in config:
        for cmd in config['execute']:
            execute(cmd)


if __name__ == "__main__":
    main()